// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ArticleCreateResultSchema
 */
export type ArticleCreateResultSchema = {
    message: string;
    count: number;
};

/**
 * ArticleCreateSchema
 */
export type ArticleCreateSchema = {
    /**
     * 文章标题
     */
    title: string;
    /**
     * 所属栏目ID列表
     */
    category_ids: Array<string>;
    /**
     * 文章内容
     */
    content: string;
    /**
     * 文章摘要
     */
    description?: string | null;
    /**
     * 封面图片URL
     */
    cover_url?: string | null;
    /**
     * 发布状态
     */
    status?: PublishStatus | null;
    /**
     * 发布时间，留空则使用当前时间
     */
    published_at?: string | null;
    /**
     * 标签ID列表
     */
    tag_ids?: Array<string> | null;
    /**
     * 专题ID列表
     */
    special_ids?: Array<string> | null;
    /**
     * 推荐位ID列表
     */
    feature_ids?: Array<string> | null;
    /**
     * 上传令牌，用于标记图片已使用
     */
    upload_token?: string | null;
};

/**
 * ArticleLiteSchema
 */
export type ArticleLiteSchema = {
    id: string;
    title: string;
    url: string;
    description?: string | null;
    cover_url?: string | null;
    status: PublishStatus;
    views: number;
    published_at?: string | null;
    created_at: string;
    updated_at: string;
    category_id: string;
    category: CategoryLiteSchema;
    creator_id: string;
    creator: UserLiteSchema;
};

/**
 * ArticleSchema
 */
export type ArticleSchema = {
    id: string;
    title: string;
    url: string;
    description?: string | null;
    cover_url?: string | null;
    status: PublishStatus;
    views: number;
    published_at?: string | null;
    created_at: string;
    updated_at: string;
    category_id: string;
    category: CategoryLiteSchema;
    creator_id: string;
    creator: UserLiteSchema;
    content: string;
    tags: Array<TagLiteSchema>;
    specials: Array<SpecialLiteSchema>;
    features: Array<FeatureLiteSchema>;
};

/**
 * ArticleUpdateSchema
 */
export type ArticleUpdateSchema = {
    /**
     * 文章标题
     */
    title?: string | null;
    /**
     * 所属栏目ID
     */
    category_id?: string | null;
    /**
     * 文章内容
     */
    content?: string | null;
    /**
     * 文章摘要
     */
    description?: string | null;
    /**
     * 封面图片URL
     */
    cover_url?: string | null;
    /**
     * 发布状态
     */
    status?: PublishStatus | null;
    /**
     * 发布时间
     */
    published_at?: string | null;
    /**
     * 标签ID列表
     */
    tag_ids?: Array<string> | null;
    /**
     * 专题ID列表
     */
    special_ids?: Array<string> | null;
    /**
     * 推荐位ID列表
     */
    feature_ids?: Array<string> | null;
    /**
     * 上传令牌，用于标记图片已使用
     */
    upload_token?: string | null;
};

/**
 * CategoryCreateSchema
 */
export type CategoryCreateSchema = {
    /**
     * 栏目名称
     */
    name: string;
    /**
     * 可用占位符{key}{year}{month}{day}{y}{m}{d}
     */
    path: string;
    /**
     * 可用占位符{key}{year}{month}{day}{y}{m}{d}{parent}
     */
    content_path: string;
    /**
     * 模板
     */
    template: string;
    title?: string | null;
    description?: string | null;
    cover_url?: string | null;
    page_size?: number | null;
    priority?: number | null;
    parent_id?: string | null;
    domain?: string | null;
};

/**
 * CategoryLiteSchema
 */
export type CategoryLiteSchema = {
    id: string;
    parent_id?: string | null;
    depth: number;
    name: string;
    title?: string | null;
    description?: string | null;
    cover_url?: string | null;
    url: string;
    page_size: number;
    priority: number;
    template: string;
    created_at: string;
    updated_at?: string | null;
    /**
     * 可用占位符{key}{year}{month}{day}{y}{m}{d}
     */
    path: string;
    /**
     * 可用占位符{key}{year}{month}{day}{y}{m}{d}{parent}
     */
    content_path: string;
    domain?: string | null;
};

/**
 * CategorySchema
 */
export type CategorySchema = {
    id: string;
    parent_id?: string | null;
    depth: number;
    name: string;
    title?: string | null;
    description?: string | null;
    cover_url?: string | null;
    url: string;
    page_size: number;
    priority: number;
    template: string;
    created_at: string;
    updated_at?: string | null;
    /**
     * 可用占位符{key}{year}{month}{day}{y}{m}{d}
     */
    path: string;
    /**
     * 可用占位符{key}{year}{month}{day}{y}{m}{d}{parent}
     */
    content_path: string;
    domain?: string | null;
    parent?: CategoryLiteSchema | null;
};

/**
 * CategoryUpdateSchema
 */
export type CategoryUpdateSchema = {
    name?: string | null;
    path?: string | null;
    content_path?: string | null;
    title?: string | null;
    description?: string | null;
    cover_url?: string | null;
    page_size?: number | null;
    priority?: number | null;
    template?: string | null;
    parent_id?: string | null;
    domain?: string | null;
};

/**
 * FeatureContentItem
 */
export type FeatureContentItem = {
    /**
     * 内容ID
     */
    content_id: string;
    /**
     * 内容标题
     */
    title: string;
};

/**
 * FeatureContentsResponse
 */
export type FeatureContentsResponse = {
    /**
     * 推荐位ID
     */
    feature_id: string;
    /**
     * 推荐位名称
     */
    name: string;
    /**
     * 内容列表
     */
    contents?: Array<FeatureContentItem>;
};

/**
 * FeatureCreateSchema
 */
export type FeatureCreateSchema = {
    /**
     * 推荐位名称
     */
    name: string;
};

/**
 * FeatureLiteSchema
 */
export type FeatureLiteSchema = {
    id: string;
    name: string;
    created_at: string;
    updated_at: string;
};

/**
 * FeatureSchema
 */
export type FeatureSchema = {
    id: string;
    name: string;
    created_at: string;
    updated_at: string;
};

/**
 * FeatureUpdateSchema
 */
export type FeatureUpdateSchema = {
    name?: string | null;
};

/**
 * PasswordChangeSchema
 */
export type PasswordChangeSchema = {
    /**
     * 当前密码
     */
    old_password: string;
    /**
     * 新密码
     */
    new_password: string;
};

/**
 * PermissionSchema
 */
export type PermissionSchema = {
    id: string;
    name: string;
    description?: string | null;
};

/**
 * PermissionUpdateSchema
 */
export type PermissionUpdateSchema = {
    name?: string | null;
    description?: string | null;
};

/**
 * PublishStatus
 */
export type PublishStatus = 'draft' | 'published' | 'archived';

/**
 * PushContentsResponseSchema
 */
export type PushContentsResponseSchema = {
    /**
     * 成功添加数量
     */
    added: number;
    /**
     * 请求添加数量
     */
    total_requested: number;
};

/**
 * PushContentsSchema
 */
export type PushContentsSchema = {
    /**
     * 内容ID列表
     */
    content_ids: Array<string>;
};

/**
 * RoleCreateSchema
 */
export type RoleCreateSchema = {
    /**
     * 角色名称
     */
    name: string;
    /**
     * 角色描述
     */
    description?: string | null;
    /**
     * 权限ID列表
     */
    permissions?: Array<string> | null;
};

/**
 * RoleLiteSchema
 */
export type RoleLiteSchema = {
    id: string;
    name: string;
    description?: string | null;
};

/**
 * RoleSchema
 */
export type RoleSchema = {
    id: string;
    name: string;
    description?: string | null;
    permissions: Array<PermissionSchema>;
};

/**
 * RoleUpdateSchema
 */
export type RoleUpdateSchema = {
    name?: string | null;
    description?: string | null;
    permissions?: Array<string> | null;
};

/**
 * SortContentsResponseSchema
 */
export type SortContentsResponseSchema = {
    /**
     * 更新数量
     */
    updated: number;
};

/**
 * SortContentsSchema
 */
export type SortContentsSchema = {
    /**
     * 排序项列表
     */
    items: Array<SortItemSchema>;
};

/**
 * SortItemSchema
 */
export type SortItemSchema = {
    /**
     * 内容ID
     */
    content_id: string;
    /**
     * 排序位置
     */
    position: number;
};

/**
 * SpecialContentItem
 */
export type SpecialContentItem = {
    /**
     * 内容ID
     */
    content_id: string;
    /**
     * 内容标题
     */
    title: string;
    /**
     * 排序位置
     */
    position: number;
    /**
     * 是否头条
     */
    headline: boolean;
    /**
     * 添加时间
     */
    added_at: string;
};

/**
 * SpecialContentsResponse
 */
export type SpecialContentsResponse = {
    /**
     * 专题ID
     */
    special_id: string;
    /**
     * 专题名称
     */
    name: string;
    /**
     * 专题标识
     */
    slug: string;
    /**
     * 专题标题
     */
    title: string;
    /**
     * 专题描述
     */
    description?: string | null;
    /**
     * 封面图片URL
     */
    cover_url?: string | null;
    /**
     * 内容列表
     */
    contents?: Array<SpecialContentItem>;
};

/**
 * SpecialCreateSchema
 */
export type SpecialCreateSchema = {
    /**
     * 专题名称
     */
    name: string;
    /**
     * 专题标识
     */
    slug: string;
    /**
     * 专题标题
     */
    title: string;
    description?: string | null;
    cover_url?: string | null;
    /**
     * 上线状态
     */
    is_active?: boolean;
    /**
     * 排序优先级
     */
    priority?: number;
    published_at?: string | null;
};

/**
 * SpecialLiteSchema
 */
export type SpecialLiteSchema = {
    id: string;
    name: string;
    slug: string;
    title: string;
    description?: string | null;
    cover_url?: string | null;
    is_active: boolean;
    priority: number;
    published_at?: string | null;
    created_at: string;
    updated_at: string;
    readonly url: string;
};

/**
 * SpecialSchema
 */
export type SpecialSchema = {
    id: string;
    name: string;
    slug: string;
    title: string;
    description?: string | null;
    cover_url?: string | null;
    is_active: boolean;
    priority: number;
    published_at?: string | null;
    created_at: string;
    updated_at: string;
    readonly url: string;
};

/**
 * SpecialUpdateSchema
 */
export type SpecialUpdateSchema = {
    name?: string | null;
    slug?: string | null;
    title?: string | null;
    description?: string | null;
    cover_url?: string | null;
    is_active?: boolean | null;
    priority?: number | null;
    published_at?: string | null;
};

/**
 * TagContentItem
 */
export type TagContentItem = {
    /**
     * 内容ID
     */
    content_id: string;
    /**
     * 内容标题
     */
    title: string;
};

/**
 * TagContentsResponse
 */
export type TagContentsResponse = {
    /**
     * 标签ID
     */
    tag_id: string;
    /**
     * 标签名称
     */
    name: string;
    /**
     * 标签标识
     */
    slug: string;
    /**
     * 内容列表
     */
    contents?: Array<TagContentItem>;
};

/**
 * TagCreateSchema
 */
export type TagCreateSchema = {
    /**
     * 标签名称
     */
    name: string;
    /**
     * URL 友好标识
     */
    slug: string;
};

/**
 * TagLiteSchema
 */
export type TagLiteSchema = {
    id: string;
    name: string;
    slug: string;
    readonly url: string;
};

/**
 * TagSchema
 */
export type TagSchema = {
    id: string;
    name: string;
    slug: string;
    created_at: string;
    updated_at: string;
    readonly url: string;
};

/**
 * TagUpdateSchema
 */
export type TagUpdateSchema = {
    name?: string | null;
    /**
     * URL 友好标识
     */
    slug?: string | null;
};

/**
 * TemplateContentSchema
 */
export type TemplateContentSchema = {
    content: string;
};

/**
 * TemplateRenameSchema
 */
export type TemplateRenameSchema = {
    name: string;
};

/**
 * UploadSchema
 */
export type UploadSchema = {
    url: string;
};

/**
 * UserCreateSchema
 */
export type UserCreateSchema = {
    /**
     * 用户名
     */
    username: string;
    email?: string | null;
    /**
     * 密码
     */
    password: string;
    is_superuser?: boolean;
    roles?: Array<string> | null;
};

/**
 * UserLiteSchema
 */
export type UserLiteSchema = {
    id: string;
    username: string;
    email?: string | null;
    is_active: boolean;
    is_superuser: boolean;
    created_at: string;
};

/**
 * UserLoginSchema
 */
export type UserLoginSchema = {
    username: string;
    password: string;
};

/**
 * UserSchema
 */
export type UserSchema = {
    id: string;
    username: string;
    email?: string | null;
    is_active: boolean;
    is_superuser: boolean;
    created_at: string;
    updated_at: string;
    roles: Array<RoleLiteSchema>;
    permissions: Array<string>;
};

/**
 * UserUpdateSchema
 */
export type UserUpdateSchema = {
    username?: string | null;
    email?: string | null;
    is_active?: boolean | null;
    password?: string | null;
    roles?: Array<string> | null;
};

/**
 * ArticleSchema
 */
export type ArticleSchemaWritable = {
    id: string;
    title: string;
    url: string;
    description?: string | null;
    cover_url?: string | null;
    status: PublishStatus;
    views: number;
    published_at?: string | null;
    created_at: string;
    updated_at: string;
    category_id: string;
    category: CategoryLiteSchema;
    creator_id: string;
    creator: UserLiteSchema;
    content: string;
    tags: Array<TagLiteSchemaWritable>;
    specials: Array<SpecialLiteSchemaWritable>;
    features: Array<FeatureLiteSchema>;
};

/**
 * SpecialLiteSchema
 */
export type SpecialLiteSchemaWritable = {
    id: string;
    name: string;
    slug: string;
    title: string;
    description?: string | null;
    cover_url?: string | null;
    is_active: boolean;
    priority: number;
    published_at?: string | null;
    created_at: string;
    updated_at: string;
};

/**
 * SpecialSchema
 */
export type SpecialSchemaWritable = {
    id: string;
    name: string;
    slug: string;
    title: string;
    description?: string | null;
    cover_url?: string | null;
    is_active: boolean;
    priority: number;
    published_at?: string | null;
    created_at: string;
    updated_at: string;
};

/**
 * TagLiteSchema
 */
export type TagLiteSchemaWritable = {
    id: string;
    name: string;
    slug: string;
};

/**
 * TagSchema
 */
export type TagSchemaWritable = {
    id: string;
    name: string;
    slug: string;
    created_at: string;
    updated_at: string;
};

export type ApiLoginLoginData = {
    body: UserLoginSchema;
    path?: never;
    query?: never;
    url: '/api/login';
};

export type ApiLoginLoginErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiLoginLoginError = ApiLoginLoginErrors[keyof ApiLoginLoginErrors];

export type ApiLoginLoginResponses = {
    /**
     * Document created, URL follows
     */
    201: UserSchema;
};

export type ApiLoginLoginResponse = ApiLoginLoginResponses[keyof ApiLoginLoginResponses];

export type ApiLogoutLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/logout';
};

export type ApiLogoutLogoutResponses = {
    /**
     * Document created, URL follows
     */
    201: unknown;
};

export type ApiMeProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type ApiMeProfileResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserSchema;
};

export type ApiMeProfileResponse = ApiMeProfileResponses[keyof ApiMeProfileResponses];

export type ApiMePasswordUpdatePasswordData = {
    body: PasswordChangeSchema;
    path?: never;
    query?: never;
    url: '/api/me/password';
};

export type ApiMePasswordUpdatePasswordErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiMePasswordUpdatePasswordError = ApiMePasswordUpdatePasswordErrors[keyof ApiMePasswordUpdatePasswordErrors];

export type ApiMePasswordUpdatePasswordResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserSchema;
};

export type ApiMePasswordUpdatePasswordResponse = ApiMePasswordUpdatePasswordResponses[keyof ApiMePasswordUpdatePasswordResponses];

export type ApiPermissionsListPermissionsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
    };
    url: '/api/permissions';
};

export type ApiPermissionsListPermissionsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiPermissionsListPermissionsError = ApiPermissionsListPermissionsErrors[keyof ApiPermissionsListPermissionsErrors];

export type ApiPermissionsListPermissionsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        items?: Array<PermissionSchema>;
        /**
         * Maximal number of items to send.
         */
        limit?: number;
        /**
         * Offset from the beginning of the query.
         */
        offset?: number;
        /**
         * Total number of items.
         */
        total?: number;
    };
};

export type ApiPermissionsListPermissionsResponse = ApiPermissionsListPermissionsResponses[keyof ApiPermissionsListPermissionsResponses];

export type ApiPermissionsItemIdUpdatePermissionData = {
    body: PermissionUpdateSchema;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/permissions/{item_id}';
};

export type ApiPermissionsItemIdUpdatePermissionErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiPermissionsItemIdUpdatePermissionError = ApiPermissionsItemIdUpdatePermissionErrors[keyof ApiPermissionsItemIdUpdatePermissionErrors];

export type ApiPermissionsItemIdUpdatePermissionResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PermissionSchema;
};

export type ApiPermissionsItemIdUpdatePermissionResponse = ApiPermissionsItemIdUpdatePermissionResponses[keyof ApiPermissionsItemIdUpdatePermissionResponses];

export type ApiRolesListRolesData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
        search?: string | null;
    };
    url: '/api/roles';
};

export type ApiRolesListRolesErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiRolesListRolesError = ApiRolesListRolesErrors[keyof ApiRolesListRolesErrors];

export type ApiRolesListRolesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        items?: Array<RoleLiteSchema>;
        /**
         * Maximal number of items to send.
         */
        limit?: number;
        /**
         * Offset from the beginning of the query.
         */
        offset?: number;
        /**
         * Total number of items.
         */
        total?: number;
    };
};

export type ApiRolesListRolesResponse = ApiRolesListRolesResponses[keyof ApiRolesListRolesResponses];

export type ApiRolesCreateRoleData = {
    body: RoleCreateSchema;
    path?: never;
    query?: never;
    url: '/api/roles';
};

export type ApiRolesCreateRoleErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiRolesCreateRoleError = ApiRolesCreateRoleErrors[keyof ApiRolesCreateRoleErrors];

export type ApiRolesCreateRoleResponses = {
    /**
     * Document created, URL follows
     */
    201: RoleSchema;
};

export type ApiRolesCreateRoleResponse = ApiRolesCreateRoleResponses[keyof ApiRolesCreateRoleResponses];

export type ApiRolesItemIdDeleteRoleData = {
    body?: never;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/roles/{item_id}';
};

export type ApiRolesItemIdDeleteRoleErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiRolesItemIdDeleteRoleError = ApiRolesItemIdDeleteRoleErrors[keyof ApiRolesItemIdDeleteRoleErrors];

export type ApiRolesItemIdDeleteRoleResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type ApiRolesItemIdDeleteRoleResponse = ApiRolesItemIdDeleteRoleResponses[keyof ApiRolesItemIdDeleteRoleResponses];

export type ApiRolesItemIdGetRoleData = {
    body?: never;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/roles/{item_id}';
};

export type ApiRolesItemIdGetRoleErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiRolesItemIdGetRoleError = ApiRolesItemIdGetRoleErrors[keyof ApiRolesItemIdGetRoleErrors];

export type ApiRolesItemIdGetRoleResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: RoleSchema;
};

export type ApiRolesItemIdGetRoleResponse = ApiRolesItemIdGetRoleResponses[keyof ApiRolesItemIdGetRoleResponses];

export type ApiRolesItemIdUpdateRoleData = {
    body: RoleUpdateSchema;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/roles/{item_id}';
};

export type ApiRolesItemIdUpdateRoleErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiRolesItemIdUpdateRoleError = ApiRolesItemIdUpdateRoleErrors[keyof ApiRolesItemIdUpdateRoleErrors];

export type ApiRolesItemIdUpdateRoleResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: RoleSchema;
};

export type ApiRolesItemIdUpdateRoleResponse = ApiRolesItemIdUpdateRoleResponses[keyof ApiRolesItemIdUpdateRoleResponses];

export type ApiUsersListUsersData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
        search?: string | null;
        is_active?: boolean | null;
    };
    url: '/api/users';
};

export type ApiUsersListUsersErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiUsersListUsersError = ApiUsersListUsersErrors[keyof ApiUsersListUsersErrors];

export type ApiUsersListUsersResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        items?: Array<UserLiteSchema>;
        /**
         * Maximal number of items to send.
         */
        limit?: number;
        /**
         * Offset from the beginning of the query.
         */
        offset?: number;
        /**
         * Total number of items.
         */
        total?: number;
    };
};

export type ApiUsersListUsersResponse = ApiUsersListUsersResponses[keyof ApiUsersListUsersResponses];

export type ApiUsersCreateUserData = {
    body: UserCreateSchema;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type ApiUsersCreateUserErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiUsersCreateUserError = ApiUsersCreateUserErrors[keyof ApiUsersCreateUserErrors];

export type ApiUsersCreateUserResponses = {
    /**
     * Document created, URL follows
     */
    201: UserSchema;
};

export type ApiUsersCreateUserResponse = ApiUsersCreateUserResponses[keyof ApiUsersCreateUserResponses];

export type ApiUsersItemIdDeleteUserData = {
    body?: never;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/users/{item_id}';
};

export type ApiUsersItemIdDeleteUserErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiUsersItemIdDeleteUserError = ApiUsersItemIdDeleteUserErrors[keyof ApiUsersItemIdDeleteUserErrors];

export type ApiUsersItemIdDeleteUserResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type ApiUsersItemIdDeleteUserResponse = ApiUsersItemIdDeleteUserResponses[keyof ApiUsersItemIdDeleteUserResponses];

export type ApiUsersItemIdGetUserData = {
    body?: never;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/users/{item_id}';
};

export type ApiUsersItemIdGetUserErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiUsersItemIdGetUserError = ApiUsersItemIdGetUserErrors[keyof ApiUsersItemIdGetUserErrors];

export type ApiUsersItemIdGetUserResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserSchema;
};

export type ApiUsersItemIdGetUserResponse = ApiUsersItemIdGetUserResponses[keyof ApiUsersItemIdGetUserResponses];

export type ApiUsersItemIdUpdateUserData = {
    body: UserUpdateSchema;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/users/{item_id}';
};

export type ApiUsersItemIdUpdateUserErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiUsersItemIdUpdateUserError = ApiUsersItemIdUpdateUserErrors[keyof ApiUsersItemIdUpdateUserErrors];

export type ApiUsersItemIdUpdateUserResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserSchema;
};

export type ApiUsersItemIdUpdateUserResponse = ApiUsersItemIdUpdateUserResponses[keyof ApiUsersItemIdUpdateUserResponses];

export type ApiCategoriesListCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
        search?: string | null;
    };
    url: '/api/categories';
};

export type ApiCategoriesListCategoriesErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiCategoriesListCategoriesError = ApiCategoriesListCategoriesErrors[keyof ApiCategoriesListCategoriesErrors];

export type ApiCategoriesListCategoriesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        items?: Array<CategoryLiteSchema>;
        /**
         * Maximal number of items to send.
         */
        limit?: number;
        /**
         * Offset from the beginning of the query.
         */
        offset?: number;
        /**
         * Total number of items.
         */
        total?: number;
    };
};

export type ApiCategoriesListCategoriesResponse = ApiCategoriesListCategoriesResponses[keyof ApiCategoriesListCategoriesResponses];

export type ApiCategoriesCreateCategoryData = {
    body: CategoryCreateSchema;
    path?: never;
    query?: never;
    url: '/api/categories';
};

export type ApiCategoriesCreateCategoryErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiCategoriesCreateCategoryError = ApiCategoriesCreateCategoryErrors[keyof ApiCategoriesCreateCategoryErrors];

export type ApiCategoriesCreateCategoryResponses = {
    /**
     * Document created, URL follows
     */
    201: CategoryLiteSchema;
};

export type ApiCategoriesCreateCategoryResponse = ApiCategoriesCreateCategoryResponses[keyof ApiCategoriesCreateCategoryResponses];

export type ApiCategoriesItemIdDeleteCategoryData = {
    body?: never;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/categories/{item_id}';
};

export type ApiCategoriesItemIdDeleteCategoryErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiCategoriesItemIdDeleteCategoryError = ApiCategoriesItemIdDeleteCategoryErrors[keyof ApiCategoriesItemIdDeleteCategoryErrors];

export type ApiCategoriesItemIdDeleteCategoryResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type ApiCategoriesItemIdDeleteCategoryResponse = ApiCategoriesItemIdDeleteCategoryResponses[keyof ApiCategoriesItemIdDeleteCategoryResponses];

export type ApiCategoriesItemIdGetCategoryData = {
    body?: never;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/categories/{item_id}';
};

export type ApiCategoriesItemIdGetCategoryErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiCategoriesItemIdGetCategoryError = ApiCategoriesItemIdGetCategoryErrors[keyof ApiCategoriesItemIdGetCategoryErrors];

export type ApiCategoriesItemIdGetCategoryResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: CategorySchema;
};

export type ApiCategoriesItemIdGetCategoryResponse = ApiCategoriesItemIdGetCategoryResponses[keyof ApiCategoriesItemIdGetCategoryResponses];

export type ApiCategoriesItemIdUpdateCategoryData = {
    body: CategoryUpdateSchema;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/categories/{item_id}';
};

export type ApiCategoriesItemIdUpdateCategoryErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiCategoriesItemIdUpdateCategoryError = ApiCategoriesItemIdUpdateCategoryErrors[keyof ApiCategoriesItemIdUpdateCategoryErrors];

export type ApiCategoriesItemIdUpdateCategoryResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: CategorySchema;
};

export type ApiCategoriesItemIdUpdateCategoryResponse = ApiCategoriesItemIdUpdateCategoryResponses[keyof ApiCategoriesItemIdUpdateCategoryResponses];

export type ApiFeaturesListFeaturesData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
        search?: string | null;
    };
    url: '/api/features';
};

export type ApiFeaturesListFeaturesErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFeaturesListFeaturesError = ApiFeaturesListFeaturesErrors[keyof ApiFeaturesListFeaturesErrors];

export type ApiFeaturesListFeaturesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        items?: Array<FeatureSchema>;
        /**
         * Maximal number of items to send.
         */
        limit?: number;
        /**
         * Offset from the beginning of the query.
         */
        offset?: number;
        /**
         * Total number of items.
         */
        total?: number;
    };
};

export type ApiFeaturesListFeaturesResponse = ApiFeaturesListFeaturesResponses[keyof ApiFeaturesListFeaturesResponses];

export type ApiFeaturesCreateFeatureData = {
    body: FeatureCreateSchema;
    path?: never;
    query?: never;
    url: '/api/features';
};

export type ApiFeaturesCreateFeatureErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFeaturesCreateFeatureError = ApiFeaturesCreateFeatureErrors[keyof ApiFeaturesCreateFeatureErrors];

export type ApiFeaturesCreateFeatureResponses = {
    /**
     * Document created, URL follows
     */
    201: FeatureSchema;
};

export type ApiFeaturesCreateFeatureResponse = ApiFeaturesCreateFeatureResponses[keyof ApiFeaturesCreateFeatureResponses];

export type ApiFeaturesItemIdDeleteFeatureData = {
    body?: never;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/features/{item_id}';
};

export type ApiFeaturesItemIdDeleteFeatureErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFeaturesItemIdDeleteFeatureError = ApiFeaturesItemIdDeleteFeatureErrors[keyof ApiFeaturesItemIdDeleteFeatureErrors];

export type ApiFeaturesItemIdDeleteFeatureResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type ApiFeaturesItemIdDeleteFeatureResponse = ApiFeaturesItemIdDeleteFeatureResponses[keyof ApiFeaturesItemIdDeleteFeatureResponses];

export type ApiFeaturesItemIdGetFeatureData = {
    body?: never;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/features/{item_id}';
};

export type ApiFeaturesItemIdGetFeatureErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFeaturesItemIdGetFeatureError = ApiFeaturesItemIdGetFeatureErrors[keyof ApiFeaturesItemIdGetFeatureErrors];

export type ApiFeaturesItemIdGetFeatureResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: FeatureSchema;
};

export type ApiFeaturesItemIdGetFeatureResponse = ApiFeaturesItemIdGetFeatureResponses[keyof ApiFeaturesItemIdGetFeatureResponses];

export type ApiFeaturesItemIdUpdateFeatureData = {
    body: FeatureUpdateSchema;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/features/{item_id}';
};

export type ApiFeaturesItemIdUpdateFeatureErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFeaturesItemIdUpdateFeatureError = ApiFeaturesItemIdUpdateFeatureErrors[keyof ApiFeaturesItemIdUpdateFeatureErrors];

export type ApiFeaturesItemIdUpdateFeatureResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: FeatureSchema;
};

export type ApiFeaturesItemIdUpdateFeatureResponse = ApiFeaturesItemIdUpdateFeatureResponses[keyof ApiFeaturesItemIdUpdateFeatureResponses];

export type ApiTagsListTagsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
        search?: string | null;
    };
    url: '/api/tags';
};

export type ApiTagsListTagsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiTagsListTagsError = ApiTagsListTagsErrors[keyof ApiTagsListTagsErrors];

export type ApiTagsListTagsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        items?: Array<TagSchema>;
        /**
         * Maximal number of items to send.
         */
        limit?: number;
        /**
         * Offset from the beginning of the query.
         */
        offset?: number;
        /**
         * Total number of items.
         */
        total?: number;
    };
};

export type ApiTagsListTagsResponse = ApiTagsListTagsResponses[keyof ApiTagsListTagsResponses];

export type ApiTagsCreateTagData = {
    body: TagCreateSchema;
    path?: never;
    query?: never;
    url: '/api/tags';
};

export type ApiTagsCreateTagErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiTagsCreateTagError = ApiTagsCreateTagErrors[keyof ApiTagsCreateTagErrors];

export type ApiTagsCreateTagResponses = {
    /**
     * Document created, URL follows
     */
    201: TagSchema;
};

export type ApiTagsCreateTagResponse = ApiTagsCreateTagResponses[keyof ApiTagsCreateTagResponses];

export type ApiTagsItemIdDeleteTagData = {
    body?: never;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/tags/{item_id}';
};

export type ApiTagsItemIdDeleteTagErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiTagsItemIdDeleteTagError = ApiTagsItemIdDeleteTagErrors[keyof ApiTagsItemIdDeleteTagErrors];

export type ApiTagsItemIdDeleteTagResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type ApiTagsItemIdDeleteTagResponse = ApiTagsItemIdDeleteTagResponses[keyof ApiTagsItemIdDeleteTagResponses];

export type ApiTagsItemIdGetTagData = {
    body?: never;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/tags/{item_id}';
};

export type ApiTagsItemIdGetTagErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiTagsItemIdGetTagError = ApiTagsItemIdGetTagErrors[keyof ApiTagsItemIdGetTagErrors];

export type ApiTagsItemIdGetTagResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TagSchema;
};

export type ApiTagsItemIdGetTagResponse = ApiTagsItemIdGetTagResponses[keyof ApiTagsItemIdGetTagResponses];

export type ApiTagsItemIdUpdateTagData = {
    body: TagUpdateSchema;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/tags/{item_id}';
};

export type ApiTagsItemIdUpdateTagErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiTagsItemIdUpdateTagError = ApiTagsItemIdUpdateTagErrors[keyof ApiTagsItemIdUpdateTagErrors];

export type ApiTagsItemIdUpdateTagResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TagSchema;
};

export type ApiTagsItemIdUpdateTagResponse = ApiTagsItemIdUpdateTagResponses[keyof ApiTagsItemIdUpdateTagResponses];

export type ApiTagsTagIdContentsListContentsData = {
    body?: never;
    path: {
        tag_id: string;
    };
    query?: never;
    url: '/api/tags/{tag_id}/contents';
};

export type ApiTagsTagIdContentsListContentsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiTagsTagIdContentsListContentsError = ApiTagsTagIdContentsListContentsErrors[keyof ApiTagsTagIdContentsListContentsErrors];

export type ApiTagsTagIdContentsListContentsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TagContentsResponse;
};

export type ApiTagsTagIdContentsListContentsResponse = ApiTagsTagIdContentsListContentsResponses[keyof ApiTagsTagIdContentsListContentsResponses];

export type ApiTagsTagIdContentsPushContentsData = {
    body: PushContentsSchema;
    path: {
        tag_id: string;
    };
    query?: never;
    url: '/api/tags/{tag_id}/contents';
};

export type ApiTagsTagIdContentsPushContentsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiTagsTagIdContentsPushContentsError = ApiTagsTagIdContentsPushContentsErrors[keyof ApiTagsTagIdContentsPushContentsErrors];

export type ApiTagsTagIdContentsPushContentsResponses = {
    /**
     * Document created, URL follows
     */
    201: PushContentsResponseSchema;
};

export type ApiTagsTagIdContentsPushContentsResponse = ApiTagsTagIdContentsPushContentsResponses[keyof ApiTagsTagIdContentsPushContentsResponses];

export type ApiTagsTagIdContentsContentIdRemoveContentData = {
    body?: never;
    path: {
        tag_id: string;
        content_id: string;
    };
    query?: never;
    url: '/api/tags/{tag_id}/contents/{content_id}';
};

export type ApiTagsTagIdContentsContentIdRemoveContentErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiTagsTagIdContentsContentIdRemoveContentError = ApiTagsTagIdContentsContentIdRemoveContentErrors[keyof ApiTagsTagIdContentsContentIdRemoveContentErrors];

export type ApiTagsTagIdContentsContentIdRemoveContentResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type ApiTagsTagIdContentsContentIdRemoveContentResponse = ApiTagsTagIdContentsContentIdRemoveContentResponses[keyof ApiTagsTagIdContentsContentIdRemoveContentResponses];

export type ApiSpecialsListSpecialsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
        /**
         * 搜索名称/标题
         */
        search?: string | null;
        /**
         * 上线状态
         */
        is_active?: boolean | null;
    };
    url: '/api/specials';
};

export type ApiSpecialsListSpecialsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiSpecialsListSpecialsError = ApiSpecialsListSpecialsErrors[keyof ApiSpecialsListSpecialsErrors];

export type ApiSpecialsListSpecialsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        items?: Array<SpecialSchema>;
        /**
         * Maximal number of items to send.
         */
        limit?: number;
        /**
         * Offset from the beginning of the query.
         */
        offset?: number;
        /**
         * Total number of items.
         */
        total?: number;
    };
};

export type ApiSpecialsListSpecialsResponse = ApiSpecialsListSpecialsResponses[keyof ApiSpecialsListSpecialsResponses];

export type ApiSpecialsCreateSpecialData = {
    body: SpecialCreateSchema;
    path?: never;
    query?: never;
    url: '/api/specials';
};

export type ApiSpecialsCreateSpecialErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiSpecialsCreateSpecialError = ApiSpecialsCreateSpecialErrors[keyof ApiSpecialsCreateSpecialErrors];

export type ApiSpecialsCreateSpecialResponses = {
    /**
     * Document created, URL follows
     */
    201: SpecialSchema;
};

export type ApiSpecialsCreateSpecialResponse = ApiSpecialsCreateSpecialResponses[keyof ApiSpecialsCreateSpecialResponses];

export type ApiSpecialsSpecialIdDeleteSpecialData = {
    body?: never;
    path: {
        special_id: string;
    };
    query?: never;
    url: '/api/specials/{special_id}';
};

export type ApiSpecialsSpecialIdDeleteSpecialErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiSpecialsSpecialIdDeleteSpecialError = ApiSpecialsSpecialIdDeleteSpecialErrors[keyof ApiSpecialsSpecialIdDeleteSpecialErrors];

export type ApiSpecialsSpecialIdDeleteSpecialResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type ApiSpecialsSpecialIdDeleteSpecialResponse = ApiSpecialsSpecialIdDeleteSpecialResponses[keyof ApiSpecialsSpecialIdDeleteSpecialResponses];

export type ApiSpecialsSpecialIdGetSpecialData = {
    body?: never;
    path: {
        special_id: string;
    };
    query?: never;
    url: '/api/specials/{special_id}';
};

export type ApiSpecialsSpecialIdGetSpecialErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiSpecialsSpecialIdGetSpecialError = ApiSpecialsSpecialIdGetSpecialErrors[keyof ApiSpecialsSpecialIdGetSpecialErrors];

export type ApiSpecialsSpecialIdGetSpecialResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: SpecialSchema;
};

export type ApiSpecialsSpecialIdGetSpecialResponse = ApiSpecialsSpecialIdGetSpecialResponses[keyof ApiSpecialsSpecialIdGetSpecialResponses];

export type ApiSpecialsSpecialIdUpdateSpecialData = {
    body: SpecialUpdateSchema;
    path: {
        special_id: string;
    };
    query?: never;
    url: '/api/specials/{special_id}';
};

export type ApiSpecialsSpecialIdUpdateSpecialErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiSpecialsSpecialIdUpdateSpecialError = ApiSpecialsSpecialIdUpdateSpecialErrors[keyof ApiSpecialsSpecialIdUpdateSpecialErrors];

export type ApiSpecialsSpecialIdUpdateSpecialResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: SpecialSchema;
};

export type ApiSpecialsSpecialIdUpdateSpecialResponse = ApiSpecialsSpecialIdUpdateSpecialResponses[keyof ApiSpecialsSpecialIdUpdateSpecialResponses];

export type ApiSpecialsSpecialIdContentsListContentsData = {
    body?: never;
    path: {
        special_id: string;
    };
    query?: never;
    url: '/api/specials/{special_id}/contents';
};

export type ApiSpecialsSpecialIdContentsListContentsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiSpecialsSpecialIdContentsListContentsError = ApiSpecialsSpecialIdContentsListContentsErrors[keyof ApiSpecialsSpecialIdContentsListContentsErrors];

export type ApiSpecialsSpecialIdContentsListContentsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: SpecialContentsResponse;
};

export type ApiSpecialsSpecialIdContentsListContentsResponse = ApiSpecialsSpecialIdContentsListContentsResponses[keyof ApiSpecialsSpecialIdContentsListContentsResponses];

export type ApiSpecialsSpecialIdContentsPushContentsData = {
    body: PushContentsSchema;
    path: {
        special_id: string;
    };
    query?: never;
    url: '/api/specials/{special_id}/contents';
};

export type ApiSpecialsSpecialIdContentsPushContentsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiSpecialsSpecialIdContentsPushContentsError = ApiSpecialsSpecialIdContentsPushContentsErrors[keyof ApiSpecialsSpecialIdContentsPushContentsErrors];

export type ApiSpecialsSpecialIdContentsPushContentsResponses = {
    /**
     * Document created, URL follows
     */
    201: PushContentsResponseSchema;
};

export type ApiSpecialsSpecialIdContentsPushContentsResponse = ApiSpecialsSpecialIdContentsPushContentsResponses[keyof ApiSpecialsSpecialIdContentsPushContentsResponses];

export type ApiSpecialsSpecialIdContentsContentIdRemoveContentData = {
    body?: never;
    path: {
        special_id: string;
        content_id: string;
    };
    query?: never;
    url: '/api/specials/{special_id}/contents/{content_id}';
};

export type ApiSpecialsSpecialIdContentsContentIdRemoveContentErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiSpecialsSpecialIdContentsContentIdRemoveContentError = ApiSpecialsSpecialIdContentsContentIdRemoveContentErrors[keyof ApiSpecialsSpecialIdContentsContentIdRemoveContentErrors];

export type ApiSpecialsSpecialIdContentsContentIdRemoveContentResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type ApiSpecialsSpecialIdContentsContentIdRemoveContentResponse = ApiSpecialsSpecialIdContentsContentIdRemoveContentResponses[keyof ApiSpecialsSpecialIdContentsContentIdRemoveContentResponses];

export type ApiSpecialsSpecialIdContentsSortSortContentsData = {
    body: SortContentsSchema;
    path: {
        special_id: string;
    };
    query?: never;
    url: '/api/specials/{special_id}/contents/sort';
};

export type ApiSpecialsSpecialIdContentsSortSortContentsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiSpecialsSpecialIdContentsSortSortContentsError = ApiSpecialsSpecialIdContentsSortSortContentsErrors[keyof ApiSpecialsSpecialIdContentsSortSortContentsErrors];

export type ApiSpecialsSpecialIdContentsSortSortContentsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: SortContentsResponseSchema;
};

export type ApiSpecialsSpecialIdContentsSortSortContentsResponse = ApiSpecialsSpecialIdContentsSortSortContentsResponses[keyof ApiSpecialsSpecialIdContentsSortSortContentsResponses];

export type ApiFeaturesFeatureIdContentsListContentsData = {
    body?: never;
    path: {
        feature_id: string;
    };
    query?: never;
    url: '/api/features/{feature_id}/contents';
};

export type ApiFeaturesFeatureIdContentsListContentsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFeaturesFeatureIdContentsListContentsError = ApiFeaturesFeatureIdContentsListContentsErrors[keyof ApiFeaturesFeatureIdContentsListContentsErrors];

export type ApiFeaturesFeatureIdContentsListContentsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: FeatureContentsResponse;
};

export type ApiFeaturesFeatureIdContentsListContentsResponse = ApiFeaturesFeatureIdContentsListContentsResponses[keyof ApiFeaturesFeatureIdContentsListContentsResponses];

export type ApiFeaturesFeatureIdContentsPushContentsData = {
    body: PushContentsSchema;
    path: {
        feature_id: string;
    };
    query?: never;
    url: '/api/features/{feature_id}/contents';
};

export type ApiFeaturesFeatureIdContentsPushContentsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFeaturesFeatureIdContentsPushContentsError = ApiFeaturesFeatureIdContentsPushContentsErrors[keyof ApiFeaturesFeatureIdContentsPushContentsErrors];

export type ApiFeaturesFeatureIdContentsPushContentsResponses = {
    /**
     * Document created, URL follows
     */
    201: PushContentsResponseSchema;
};

export type ApiFeaturesFeatureIdContentsPushContentsResponse = ApiFeaturesFeatureIdContentsPushContentsResponses[keyof ApiFeaturesFeatureIdContentsPushContentsResponses];

export type ApiFeaturesFeatureIdContentsContentIdRemoveContentData = {
    body?: never;
    path: {
        feature_id: string;
        content_id: string;
    };
    query?: never;
    url: '/api/features/{feature_id}/contents/{content_id}';
};

export type ApiFeaturesFeatureIdContentsContentIdRemoveContentErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFeaturesFeatureIdContentsContentIdRemoveContentError = ApiFeaturesFeatureIdContentsContentIdRemoveContentErrors[keyof ApiFeaturesFeatureIdContentsContentIdRemoveContentErrors];

export type ApiFeaturesFeatureIdContentsContentIdRemoveContentResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type ApiFeaturesFeatureIdContentsContentIdRemoveContentResponse = ApiFeaturesFeatureIdContentsContentIdRemoveContentResponses[keyof ApiFeaturesFeatureIdContentsContentIdRemoveContentResponses];

export type ApiArticlesListArticlesData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
        search?: string | null;
    };
    url: '/api/articles';
};

export type ApiArticlesListArticlesErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiArticlesListArticlesError = ApiArticlesListArticlesErrors[keyof ApiArticlesListArticlesErrors];

export type ApiArticlesListArticlesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        items?: Array<ArticleLiteSchema>;
        /**
         * Maximal number of items to send.
         */
        limit?: number;
        /**
         * Offset from the beginning of the query.
         */
        offset?: number;
        /**
         * Total number of items.
         */
        total?: number;
    };
};

export type ApiArticlesListArticlesResponse = ApiArticlesListArticlesResponses[keyof ApiArticlesListArticlesResponses];

export type ApiArticlesCreateArticleData = {
    body: ArticleCreateSchema;
    path?: never;
    query?: never;
    url: '/api/articles';
};

export type ApiArticlesCreateArticleErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiArticlesCreateArticleError = ApiArticlesCreateArticleErrors[keyof ApiArticlesCreateArticleErrors];

export type ApiArticlesCreateArticleResponses = {
    /**
     * Document created, URL follows
     */
    201: ArticleCreateResultSchema;
};

export type ApiArticlesCreateArticleResponse = ApiArticlesCreateArticleResponses[keyof ApiArticlesCreateArticleResponses];

export type ApiArticlesItemIdDeleteArticleData = {
    body?: never;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/articles/{item_id}';
};

export type ApiArticlesItemIdDeleteArticleErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiArticlesItemIdDeleteArticleError = ApiArticlesItemIdDeleteArticleErrors[keyof ApiArticlesItemIdDeleteArticleErrors];

export type ApiArticlesItemIdDeleteArticleResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type ApiArticlesItemIdDeleteArticleResponse = ApiArticlesItemIdDeleteArticleResponses[keyof ApiArticlesItemIdDeleteArticleResponses];

export type ApiArticlesItemIdGetArticleData = {
    body?: never;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/articles/{item_id}';
};

export type ApiArticlesItemIdGetArticleErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiArticlesItemIdGetArticleError = ApiArticlesItemIdGetArticleErrors[keyof ApiArticlesItemIdGetArticleErrors];

export type ApiArticlesItemIdGetArticleResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ArticleSchema;
};

export type ApiArticlesItemIdGetArticleResponse = ApiArticlesItemIdGetArticleResponses[keyof ApiArticlesItemIdGetArticleResponses];

export type ApiArticlesItemIdUpdateArticleData = {
    body: ArticleUpdateSchema;
    path: {
        item_id: string;
    };
    query?: never;
    url: '/api/articles/{item_id}';
};

export type ApiArticlesItemIdUpdateArticleErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiArticlesItemIdUpdateArticleError = ApiArticlesItemIdUpdateArticleErrors[keyof ApiArticlesItemIdUpdateArticleErrors];

export type ApiArticlesItemIdUpdateArticleResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ArticleSchema;
};

export type ApiArticlesItemIdUpdateArticleResponse = ApiArticlesItemIdUpdateArticleResponses[keyof ApiArticlesItemIdUpdateArticleResponses];

export type ApiUploadUploadData = {
    body: {
        file?: Blob | File;
    };
    path?: never;
    query: {
        upload_token: string;
    };
    url: '/api/upload';
};

export type ApiUploadUploadErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiUploadUploadError = ApiUploadUploadErrors[keyof ApiUploadUploadErrors];

export type ApiUploadUploadResponses = {
    /**
     * Document created, URL follows
     */
    201: UploadSchema;
};

export type ApiUploadUploadResponse = ApiUploadUploadResponses[keyof ApiUploadUploadResponses];

export type ApiTemplatesFilePathDeleteTemplateData = {
    body?: never;
    path: {
        /**
         * 模板文件路径
         */
        file_path: string;
    };
    query?: never;
    url: '/api/templates/{file_path}';
};

export type ApiTemplatesFilePathDeleteTemplateErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiTemplatesFilePathDeleteTemplateError = ApiTemplatesFilePathDeleteTemplateErrors[keyof ApiTemplatesFilePathDeleteTemplateErrors];

export type ApiTemplatesFilePathDeleteTemplateResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type ApiTemplatesFilePathDeleteTemplateResponse = ApiTemplatesFilePathDeleteTemplateResponses[keyof ApiTemplatesFilePathDeleteTemplateResponses];

export type ApiTemplatesFilePathGetTemplateData = {
    body?: never;
    path: {
        /**
         * 模板文件路径
         */
        file_path: string;
    };
    query?: never;
    url: '/api/templates/{file_path}';
};

export type ApiTemplatesFilePathGetTemplateErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiTemplatesFilePathGetTemplateError = ApiTemplatesFilePathGetTemplateErrors[keyof ApiTemplatesFilePathGetTemplateErrors];

export type ApiTemplatesFilePathGetTemplateResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TemplateContentSchema;
};

export type ApiTemplatesFilePathGetTemplateResponse = ApiTemplatesFilePathGetTemplateResponses[keyof ApiTemplatesFilePathGetTemplateResponses];

export type ApiTemplatesFilePathRenameTemplateData = {
    body: TemplateRenameSchema;
    path: {
        /**
         * 模板文件路径
         */
        file_path: string;
    };
    query?: never;
    url: '/api/templates/{file_path}';
};

export type ApiTemplatesFilePathRenameTemplateErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiTemplatesFilePathRenameTemplateError = ApiTemplatesFilePathRenameTemplateErrors[keyof ApiTemplatesFilePathRenameTemplateErrors];

export type ApiTemplatesFilePathRenameTemplateResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: unknown;
};

export type ApiTemplatesFilePathSaveTemplateData = {
    body: TemplateContentSchema;
    path: {
        /**
         * 模板文件路径
         */
        file_path: string;
    };
    query?: never;
    url: '/api/templates/{file_path}';
};

export type ApiTemplatesFilePathSaveTemplateErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiTemplatesFilePathSaveTemplateError = ApiTemplatesFilePathSaveTemplateErrors[keyof ApiTemplatesFilePathSaveTemplateErrors];

export type ApiTemplatesFilePathSaveTemplateResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: unknown;
};

export type ApiTemplatesOptionsGetTemplateOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/templates/options';
};

export type ApiTemplatesOptionsGetTemplateOptionsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<string>;
};

export type ApiTemplatesOptionsGetTemplateOptionsResponse = ApiTemplatesOptionsGetTemplateOptionsResponses[keyof ApiTemplatesOptionsGetTemplateOptionsResponses];

export type ApiTemplatesListTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/templates';
};

export type ApiTemplatesListTemplatesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<string>;
};

export type ApiTemplatesListTemplatesResponse = ApiTemplatesListTemplatesResponses[keyof ApiTemplatesListTemplatesResponses];
