// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * ArticleCreateResultSchema
 */
export const articleCreateResultSchema = z.object({
    message: z.string(),
    count: z.int()
});

/**
 * CategoryCreateSchema
 */
export const categoryCreateSchema = z.object({
    name: z.string().min(1).max(100),
    path: z.string().min(1),
    content_path: z.string().min(1),
    template: z.string().min(1).max(255),
    title: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    page_size: z.optional(z.union([
        z.int().default(15),
        z.null()
    ])).default(15),
    priority: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    parent_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    domain: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * CategoryLiteSchema
 */
export const categoryLiteSchema = z.object({
    id: z.uuid(),
    parent_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    depth: z.int(),
    name: z.string(),
    title: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    url: z.string(),
    page_size: z.int(),
    priority: z.int(),
    template: z.string(),
    created_at: z.iso.datetime(),
    updated_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    path: z.string().min(1),
    content_path: z.string().min(1),
    domain: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * CategorySchema
 */
export const categorySchema = z.object({
    id: z.uuid(),
    parent_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    depth: z.int(),
    name: z.string(),
    title: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    url: z.string(),
    page_size: z.int(),
    priority: z.int(),
    template: z.string(),
    created_at: z.iso.datetime(),
    updated_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    path: z.string().min(1),
    content_path: z.string().min(1),
    domain: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    parent: z.optional(z.union([
        categoryLiteSchema,
        z.null()
    ]))
});

/**
 * CategoryUpdateSchema
 */
export const categoryUpdateSchema = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    path: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    content_path: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    title: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    page_size: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    priority: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    template: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    parent_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    domain: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * FeatureContentItem
 */
export const featureContentItem = z.object({
    content_id: z.uuid(),
    title: z.string()
});

/**
 * FeatureContentsResponse
 */
export const featureContentsResponse = z.object({
    feature_id: z.uuid(),
    name: z.string(),
    contents: z.optional(z.array(featureContentItem))
});

/**
 * FeatureCreateSchema
 */
export const featureCreateSchema = z.object({
    name: z.string().min(1).max(100)
});

/**
 * FeatureLiteSchema
 */
export const featureLiteSchema = z.object({
    id: z.uuid(),
    name: z.string(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

/**
 * FeatureSchema
 */
export const featureSchema = z.object({
    id: z.uuid(),
    name: z.string(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

/**
 * FeatureUpdateSchema
 */
export const featureUpdateSchema = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * PasswordChangeSchema
 */
export const passwordChangeSchema = z.object({
    old_password: z.string().min(1),
    new_password: z.string().min(6)
});

/**
 * PermissionSchema
 */
export const permissionSchema = z.object({
    id: z.uuid(),
    name: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * PermissionUpdateSchema
 */
export const permissionUpdateSchema = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * PublishStatus
 */
export const publishStatus = z.enum([
    'draft',
    'published',
    'archived'
]);

/**
 * ArticleCreateSchema
 */
export const articleCreateSchema = z.object({
    title: z.string().min(1).max(255),
    category_ids: z.array(z.uuid()).min(1),
    content: z.string().min(1),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    status: z.optional(z.union([
        publishStatus,
        z.null()
    ])),
    published_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    tag_ids: z.optional(z.union([
        z.array(z.uuid()),
        z.null()
    ])),
    special_ids: z.optional(z.union([
        z.array(z.uuid()),
        z.null()
    ])),
    feature_ids: z.optional(z.union([
        z.array(z.uuid()),
        z.null()
    ])),
    upload_token: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * ArticleUpdateSchema
 */
export const articleUpdateSchema = z.object({
    title: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    category_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    content: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    status: z.optional(z.union([
        publishStatus,
        z.null()
    ])),
    published_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    tag_ids: z.optional(z.union([
        z.array(z.uuid()),
        z.null()
    ])),
    special_ids: z.optional(z.union([
        z.array(z.uuid()),
        z.null()
    ])),
    feature_ids: z.optional(z.union([
        z.array(z.uuid()),
        z.null()
    ])),
    upload_token: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * PushContentsResponseSchema
 */
export const pushContentsResponseSchema = z.object({
    added: z.int(),
    total_requested: z.int()
});

/**
 * PushContentsSchema
 */
export const pushContentsSchema = z.object({
    content_ids: z.array(z.uuid()).min(1)
});

/**
 * RoleCreateSchema
 */
export const roleCreateSchema = z.object({
    name: z.string().min(1).max(100),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    permissions: z.optional(z.union([
        z.array(z.uuid()),
        z.null()
    ]))
});

/**
 * RoleLiteSchema
 */
export const roleLiteSchema = z.object({
    id: z.uuid(),
    name: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * RoleSchema
 */
export const roleSchema = z.object({
    id: z.uuid(),
    name: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    permissions: z.array(permissionSchema)
});

/**
 * RoleUpdateSchema
 */
export const roleUpdateSchema = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    permissions: z.optional(z.union([
        z.array(z.uuid()),
        z.null()
    ]))
});

/**
 * SortContentsResponseSchema
 */
export const sortContentsResponseSchema = z.object({
    updated: z.int()
});

/**
 * SortItemSchema
 */
export const sortItemSchema = z.object({
    content_id: z.uuid(),
    position: z.int().gte(0)
});

/**
 * SortContentsSchema
 */
export const sortContentsSchema = z.object({
    items: z.array(sortItemSchema)
});

/**
 * SpecialContentItem
 */
export const specialContentItem = z.object({
    content_id: z.uuid(),
    title: z.string(),
    position: z.int(),
    headline: z.boolean(),
    added_at: z.iso.datetime()
});

/**
 * SpecialContentsResponse
 */
export const specialContentsResponse = z.object({
    special_id: z.uuid(),
    name: z.string(),
    slug: z.string(),
    title: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    contents: z.optional(z.array(specialContentItem))
});

/**
 * SpecialCreateSchema
 */
export const specialCreateSchema = z.object({
    name: z.string().min(1).max(100),
    slug: z.string().max(100),
    title: z.string().min(1).max(255),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_active: z.optional(z.boolean()).default(false),
    priority: z.optional(z.int()).default(0),
    published_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ]))
});

/**
 * SpecialLiteSchema
 */
export const specialLiteSchema = z.object({
    id: z.uuid(),
    name: z.string(),
    slug: z.string(),
    title: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_active: z.boolean(),
    priority: z.int(),
    published_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    url: z.string().readonly()
});

/**
 * SpecialSchema
 */
export const specialSchema = z.object({
    id: z.uuid(),
    name: z.string(),
    slug: z.string(),
    title: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_active: z.boolean(),
    priority: z.int(),
    published_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    url: z.string().readonly()
});

/**
 * SpecialUpdateSchema
 */
export const specialUpdateSchema = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    slug: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    title: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_active: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    priority: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    published_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ]))
});

/**
 * TagContentItem
 */
export const tagContentItem = z.object({
    content_id: z.uuid(),
    title: z.string()
});

/**
 * TagContentsResponse
 */
export const tagContentsResponse = z.object({
    tag_id: z.uuid(),
    name: z.string(),
    slug: z.string(),
    contents: z.optional(z.array(tagContentItem))
});

/**
 * TagCreateSchema
 */
export const tagCreateSchema = z.object({
    name: z.string().min(1).max(100),
    slug: z.string().max(100)
});

/**
 * TagLiteSchema
 */
export const tagLiteSchema = z.object({
    id: z.uuid(),
    name: z.string(),
    slug: z.string(),
    url: z.string().readonly()
});

/**
 * TagSchema
 */
export const tagSchema = z.object({
    id: z.uuid(),
    name: z.string(),
    slug: z.string(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    url: z.string().readonly()
});

/**
 * TagUpdateSchema
 */
export const tagUpdateSchema = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    slug: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * TemplateContentSchema
 */
export const templateContentSchema = z.object({
    content: z.string()
});

/**
 * TemplateRenameSchema
 */
export const templateRenameSchema = z.object({
    name: z.string()
});

/**
 * UploadSchema
 */
export const uploadSchema = z.object({
    url: z.string()
});

/**
 * UserCreateSchema
 */
export const userCreateSchema = z.object({
    username: z.string().min(2).max(100),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    password: z.string().min(6),
    is_superuser: z.optional(z.boolean()).default(false),
    roles: z.optional(z.union([
        z.array(z.uuid()),
        z.null()
    ]))
});

/**
 * UserLiteSchema
 */
export const userLiteSchema = z.object({
    id: z.uuid(),
    username: z.string(),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_active: z.boolean(),
    is_superuser: z.boolean(),
    created_at: z.iso.datetime()
});

/**
 * ArticleLiteSchema
 */
export const articleLiteSchema = z.object({
    id: z.uuid(),
    title: z.string(),
    url: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    status: publishStatus,
    views: z.int(),
    published_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    category_id: z.uuid(),
    category: categoryLiteSchema,
    creator_id: z.uuid(),
    creator: userLiteSchema
});

/**
 * ArticleSchema
 */
export const articleSchema = z.object({
    id: z.uuid(),
    title: z.string(),
    url: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    status: publishStatus,
    views: z.int(),
    published_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    category_id: z.uuid(),
    category: categoryLiteSchema,
    creator_id: z.uuid(),
    creator: userLiteSchema,
    content: z.string(),
    tags: z.array(tagLiteSchema),
    specials: z.array(specialLiteSchema),
    features: z.array(featureLiteSchema)
});

/**
 * UserLoginSchema
 */
export const userLoginSchema = z.object({
    username: z.string(),
    password: z.string()
});

/**
 * UserSchema
 */
export const userSchema = z.object({
    id: z.uuid(),
    username: z.string(),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_active: z.boolean(),
    is_superuser: z.boolean(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    roles: z.array(roleLiteSchema),
    permissions: z.array(z.string())
});

/**
 * UserUpdateSchema
 */
export const userUpdateSchema = z.object({
    username: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_active: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    password: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    roles: z.optional(z.union([
        z.array(z.uuid()),
        z.null()
    ]))
});

/**
 * SpecialLiteSchema
 */
export const specialLiteSchemaWritable = z.object({
    id: z.uuid(),
    name: z.string(),
    slug: z.string(),
    title: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_active: z.boolean(),
    priority: z.int(),
    published_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

/**
 * SpecialSchema
 */
export const specialSchemaWritable = z.object({
    id: z.uuid(),
    name: z.string(),
    slug: z.string(),
    title: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_active: z.boolean(),
    priority: z.int(),
    published_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

/**
 * TagLiteSchema
 */
export const tagLiteSchemaWritable = z.object({
    id: z.uuid(),
    name: z.string(),
    slug: z.string()
});

/**
 * ArticleSchema
 */
export const articleSchemaWritable = z.object({
    id: z.uuid(),
    title: z.string(),
    url: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cover_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    status: publishStatus,
    views: z.int(),
    published_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    category_id: z.uuid(),
    category: categoryLiteSchema,
    creator_id: z.uuid(),
    creator: userLiteSchema,
    content: z.string(),
    tags: z.array(tagLiteSchemaWritable),
    specials: z.array(specialLiteSchemaWritable),
    features: z.array(featureLiteSchema)
});

/**
 * TagSchema
 */
export const tagSchemaWritable = z.object({
    id: z.uuid(),
    name: z.string(),
    slug: z.string(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

export const zApiLoginLoginData = z.object({
    body: userLoginSchema,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Document created, URL follows
 */
export const zApiLoginLoginResponse = userSchema;

export const zApiLogoutLogoutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zApiMeProfileData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiMeProfileResponse = userSchema;

export const zApiMePasswordUpdatePasswordData = z.object({
    body: passwordChangeSchema,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiMePasswordUpdatePasswordResponse = userSchema;

export const zApiPermissionsListPermissionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().gte(1)).default(1),
        page_size: z.optional(z.int().gte(1).lte(100)).default(10)
    }))
});

/**
 * Request fulfilled, document follows
 */
export const zApiPermissionsListPermissionsResponse = z.object({
    items: z.optional(z.array(permissionSchema)),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    total: z.optional(z.int())
});

export const zApiPermissionsItemIdUpdatePermissionData = z.object({
    body: permissionUpdateSchema,
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiPermissionsItemIdUpdatePermissionResponse = permissionSchema;

export const zApiRolesListRolesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().gte(1)).default(1),
        page_size: z.optional(z.int().gte(1).lte(100)).default(10),
        search: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    }))
});

/**
 * Request fulfilled, document follows
 */
export const zApiRolesListRolesResponse = z.object({
    items: z.optional(z.array(roleLiteSchema)),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    total: z.optional(z.int())
});

export const zApiRolesCreateRoleData = z.object({
    body: roleCreateSchema,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Document created, URL follows
 */
export const zApiRolesCreateRoleResponse = roleSchema;

export const zApiRolesItemIdDeleteRoleData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, nothing follows
 */
export const zApiRolesItemIdDeleteRoleResponse = z.void();

export const zApiRolesItemIdGetRoleData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiRolesItemIdGetRoleResponse = roleSchema;

export const zApiRolesItemIdUpdateRoleData = z.object({
    body: roleUpdateSchema,
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiRolesItemIdUpdateRoleResponse = roleSchema;

export const zApiUsersListUsersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().gte(1)).default(1),
        page_size: z.optional(z.int().gte(1).lte(100)).default(10),
        search: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        is_active: z.optional(z.union([
            z.boolean(),
            z.null()
        ]))
    }))
});

/**
 * Request fulfilled, document follows
 */
export const zApiUsersListUsersResponse = z.object({
    items: z.optional(z.array(userLiteSchema)),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    total: z.optional(z.int())
});

export const zApiUsersCreateUserData = z.object({
    body: userCreateSchema,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Document created, URL follows
 */
export const zApiUsersCreateUserResponse = userSchema;

export const zApiUsersItemIdDeleteUserData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, nothing follows
 */
export const zApiUsersItemIdDeleteUserResponse = z.void();

export const zApiUsersItemIdGetUserData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiUsersItemIdGetUserResponse = userSchema;

export const zApiUsersItemIdUpdateUserData = z.object({
    body: userUpdateSchema,
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiUsersItemIdUpdateUserResponse = userSchema;

export const zApiCategoriesListCategoriesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().gte(1)).default(1),
        page_size: z.optional(z.int().gte(1).lte(100)).default(10),
        search: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    }))
});

/**
 * Request fulfilled, document follows
 */
export const zApiCategoriesListCategoriesResponse = z.object({
    items: z.optional(z.array(categoryLiteSchema)),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    total: z.optional(z.int())
});

export const zApiCategoriesCreateCategoryData = z.object({
    body: categoryCreateSchema,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Document created, URL follows
 */
export const zApiCategoriesCreateCategoryResponse = categoryLiteSchema;

export const zApiCategoriesItemIdDeleteCategoryData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, nothing follows
 */
export const zApiCategoriesItemIdDeleteCategoryResponse = z.void();

export const zApiCategoriesItemIdGetCategoryData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiCategoriesItemIdGetCategoryResponse = categorySchema;

export const zApiCategoriesItemIdUpdateCategoryData = z.object({
    body: categoryUpdateSchema,
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiCategoriesItemIdUpdateCategoryResponse = categorySchema;

export const zApiFeaturesListFeaturesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().gte(1)).default(1),
        page_size: z.optional(z.int().gte(1).lte(100)).default(10),
        search: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    }))
});

/**
 * Request fulfilled, document follows
 */
export const zApiFeaturesListFeaturesResponse = z.object({
    items: z.optional(z.array(featureSchema)),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    total: z.optional(z.int())
});

export const zApiFeaturesCreateFeatureData = z.object({
    body: featureCreateSchema,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Document created, URL follows
 */
export const zApiFeaturesCreateFeatureResponse = featureSchema;

export const zApiFeaturesItemIdDeleteFeatureData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, nothing follows
 */
export const zApiFeaturesItemIdDeleteFeatureResponse = z.void();

export const zApiFeaturesItemIdGetFeatureData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiFeaturesItemIdGetFeatureResponse = featureSchema;

export const zApiFeaturesItemIdUpdateFeatureData = z.object({
    body: featureUpdateSchema,
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiFeaturesItemIdUpdateFeatureResponse = featureSchema;

export const zApiTagsListTagsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().gte(1)).default(1),
        page_size: z.optional(z.int().gte(1).lte(100)).default(10),
        search: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    }))
});

/**
 * Request fulfilled, document follows
 */
export const zApiTagsListTagsResponse = z.object({
    items: z.optional(z.array(tagSchema)),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    total: z.optional(z.int())
});

export const zApiTagsCreateTagData = z.object({
    body: tagCreateSchema,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Document created, URL follows
 */
export const zApiTagsCreateTagResponse = tagSchema;

export const zApiTagsItemIdDeleteTagData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, nothing follows
 */
export const zApiTagsItemIdDeleteTagResponse = z.void();

export const zApiTagsItemIdGetTagData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiTagsItemIdGetTagResponse = tagSchema;

export const zApiTagsItemIdUpdateTagData = z.object({
    body: tagUpdateSchema,
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiTagsItemIdUpdateTagResponse = tagSchema;

export const zApiTagsTagIdContentsListContentsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        tag_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiTagsTagIdContentsListContentsResponse = tagContentsResponse;

export const zApiTagsTagIdContentsPushContentsData = z.object({
    body: pushContentsSchema,
    path: z.object({
        tag_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Document created, URL follows
 */
export const zApiTagsTagIdContentsPushContentsResponse = pushContentsResponseSchema;

export const zApiTagsTagIdContentsContentIdRemoveContentData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        tag_id: z.uuid(),
        content_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, nothing follows
 */
export const zApiTagsTagIdContentsContentIdRemoveContentResponse = z.void();

export const zApiSpecialsListSpecialsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().gte(1)).default(1),
        page_size: z.optional(z.int().gte(1).lte(100)).default(10),
        search: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        is_active: z.optional(z.union([
            z.boolean(),
            z.null()
        ]))
    }))
});

/**
 * Request fulfilled, document follows
 */
export const zApiSpecialsListSpecialsResponse = z.object({
    items: z.optional(z.array(specialSchema)),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    total: z.optional(z.int())
});

export const zApiSpecialsCreateSpecialData = z.object({
    body: specialCreateSchema,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Document created, URL follows
 */
export const zApiSpecialsCreateSpecialResponse = specialSchema;

export const zApiSpecialsSpecialIdDeleteSpecialData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        special_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, nothing follows
 */
export const zApiSpecialsSpecialIdDeleteSpecialResponse = z.void();

export const zApiSpecialsSpecialIdGetSpecialData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        special_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiSpecialsSpecialIdGetSpecialResponse = specialSchema;

export const zApiSpecialsSpecialIdUpdateSpecialData = z.object({
    body: specialUpdateSchema,
    path: z.object({
        special_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiSpecialsSpecialIdUpdateSpecialResponse = specialSchema;

export const zApiSpecialsSpecialIdContentsListContentsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        special_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiSpecialsSpecialIdContentsListContentsResponse = specialContentsResponse;

export const zApiSpecialsSpecialIdContentsPushContentsData = z.object({
    body: pushContentsSchema,
    path: z.object({
        special_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Document created, URL follows
 */
export const zApiSpecialsSpecialIdContentsPushContentsResponse = pushContentsResponseSchema;

export const zApiSpecialsSpecialIdContentsContentIdRemoveContentData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        special_id: z.uuid(),
        content_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, nothing follows
 */
export const zApiSpecialsSpecialIdContentsContentIdRemoveContentResponse = z.void();

export const zApiSpecialsSpecialIdContentsSortSortContentsData = z.object({
    body: sortContentsSchema,
    path: z.object({
        special_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiSpecialsSpecialIdContentsSortSortContentsResponse = sortContentsResponseSchema;

export const zApiFeaturesFeatureIdContentsListContentsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        feature_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiFeaturesFeatureIdContentsListContentsResponse = featureContentsResponse;

export const zApiFeaturesFeatureIdContentsPushContentsData = z.object({
    body: pushContentsSchema,
    path: z.object({
        feature_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Document created, URL follows
 */
export const zApiFeaturesFeatureIdContentsPushContentsResponse = pushContentsResponseSchema;

export const zApiFeaturesFeatureIdContentsContentIdRemoveContentData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        feature_id: z.uuid(),
        content_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, nothing follows
 */
export const zApiFeaturesFeatureIdContentsContentIdRemoveContentResponse = z.void();

export const zApiArticlesListArticlesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().gte(1)).default(1),
        page_size: z.optional(z.int().gte(1).lte(100)).default(10),
        search: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    }))
});

/**
 * Request fulfilled, document follows
 */
export const zApiArticlesListArticlesResponse = z.object({
    items: z.optional(z.array(articleLiteSchema)),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    total: z.optional(z.int())
});

export const zApiArticlesCreateArticleData = z.object({
    body: articleCreateSchema,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Document created, URL follows
 */
export const zApiArticlesCreateArticleResponse = articleCreateResultSchema;

export const zApiArticlesItemIdDeleteArticleData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, nothing follows
 */
export const zApiArticlesItemIdDeleteArticleResponse = z.void();

export const zApiArticlesItemIdGetArticleData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiArticlesItemIdGetArticleResponse = articleSchema;

export const zApiArticlesItemIdUpdateArticleData = z.object({
    body: articleUpdateSchema,
    path: z.object({
        item_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiArticlesItemIdUpdateArticleResponse = articleSchema;

export const zApiUploadUploadData = z.object({
    body: z.object({
        file: z.optional(z.string())
    }),
    path: z.optional(z.never()),
    query: z.object({
        upload_token: z.string()
    })
});

/**
 * Document created, URL follows
 */
export const zApiUploadUploadResponse = uploadSchema;

export const zApiTemplatesFilePathDeleteTemplateData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        file_path: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, nothing follows
 */
export const zApiTemplatesFilePathDeleteTemplateResponse = z.void();

export const zApiTemplatesFilePathGetTemplateData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        file_path: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiTemplatesFilePathGetTemplateResponse = templateContentSchema;

export const zApiTemplatesFilePathRenameTemplateData = z.object({
    body: templateRenameSchema,
    path: z.object({
        file_path: z.string()
    }),
    query: z.optional(z.never())
});

export const zApiTemplatesFilePathSaveTemplateData = z.object({
    body: templateContentSchema,
    path: z.object({
        file_path: z.string()
    }),
    query: z.optional(z.never())
});

export const zApiTemplatesOptionsGetTemplateOptionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiTemplatesOptionsGetTemplateOptionsResponse = z.array(z.string());

export const zApiTemplatesListTemplatesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Request fulfilled, document follows
 */
export const zApiTemplatesListTemplatesResponse = z.array(z.string());
